rubyバージョン修正
yuki-snow1823/diary pull request #13
Opened 2023-02-10 15:37 UTC by pchm13

2023-02-10 15:40 UTC, yuki-snow1823 requested changes
@pchm13 
descriptionにこちら追記お願いします👍

```
DockerのRubyの公式のイメージは3.2を指定すると最新の3.2.1を指定しまいます。
そのため、buildしなおした際や新しく環境構築をした際に矛盾してエラーが出るので、取得するバージョンを固定しました。
```

あとはコミットメッセージは、やった行為ではなく「何故それをしたのか」に特化すると良さそうです🙆‍♂️
（やったことはコードを見ると分かる前提のため）

2023-02-10 15:45 UTC, yuki-snow1823 commented
@pchm13 
あ、あとDockerfile（本番用ファイル）の変更もお願いします🙏

2023-02-10 15:48 UTC, pchm13 commented
> あとはコミットメッセージは、やった行為ではなく「何故それをしたのか」に特化すると良さそうです🙆‍♂️
（やったことはコードを見ると分かる前提のため）

レビュー有難うございます！
コミット名の件了解です
勉強になります！

2023-02-10 15:52 UTC, yuki-snow1823 approved these changes
![LGTM](https://image.lgtmoon.dev/197037)

2023-02-10 15:53 UTC, merged

2023-02-18 05:11 UTC, yuki-snow1823 commented on backend/Dockerfile
> -FROM ruby:3.2
与謝野晶子

2023-02-18 05:11 UTC, yuki-snow1823 reviewed
レビュー通知のテスト