記念すべき最初のgraphqlに関するRSpec
yuki-snow1823/diary pull request #58
Opened 2023-06-17 08:39 UTC by DaisukeShinoku

※ 詳細は後日書くやで

2023-07-11 02:19 UTC, yuki-snow1823 requested changes
@DaisukeShinoku 
ちょっと手元で動作確認できないので、一旦コードのレビューだけさせていただきました！！

こんな感じでコマンド実行するとサーバーが立ち上がっちゃうのでなんとかします。

<img width="555" alt="スクリーンショット 2023-07-11 11 08 56" src="https://github.com/yuki-snow1823/diary/assets/59280290/be65ac65-5336-4b6d-a8aa-77a52cbe47f0">

2023-07-11 02:19 UTC, yuki-snow1823 commented on backend/spec/requests/journal/create_journal_spec.rb
> +    context '紐付いているユーザーが正しい' do
「紐づく」「正しい」という表現が少し冗長だと思いました！
また、今回はcreateのspecなので作成の際はユーザーが正しいかどうかは関係なさそうかな？と思いました。

自分が勘違いしているかもしれないので、ここで @DaisukeShinoku さんが正しい、というのをどう捉えていらしたかお聞きしたいです！

表現に関しては例えば、一番上のcontextを`ユーザーがログインしている場合`にして、次のcontextを`titleが存在しない場合`そしてitを`journalが作成されない`にすると思います。

2023-07-11 02:19 UTC, yuki-snow1823 commented on backend/spec/requests/journal/create_journal_spec.rb
> +          expect(e.record.errors.full_messages).to include("Title can't be blank")
作成されないテストは、一般にbe_invalidなどを使うと良いかなと思ったのですがいかがでしょうか。

このテストケースだと「エラーメッセージが返ること」をテストしているように思います👀

こんなイメージでした。
```
memo = Memo.create!(title: "", content: "")
expect(memo).to be_invalid
```

2023-07-11 02:19 UTC, yuki-snow1823 commented on backend/spec/requests/journal/delete_journal_spec.rb
> +end
ここのcontext-itの書き方とても良いと感じました！！

[IMO]「存在するjournal」は自分なら「対象のJournalが存在している場合」にしますね。理由として、削除しようとすることは「RSpec.describe Mutations::DeleteJournal」で表現できていそうだなと思いました。

2023-07-11 11:27 UTC, DaisukeShinoku commented on backend/spec/requests/journal/create_journal_spec.rb
> +    context '紐付いているユーザーが正しい' do
> 正しい、というのをどう捉えていらしたか

```
  context 'ユーザーに紐付く' do
    context '紐付いているユーザーが正しい' do
      # DBに存在するユーザーを指定している
    end

    context '紐付けようとしているユーザーが存在しない' do
        # DBに存在しないユーザーを指定している
      end
    end
  end

  context 'ユーザーに紐付かない' do
    # user_id が  nil のことを書いている
  end
```

という分け方をしていたのでこの書き方になっています。
なので日本語を修正するとしたら

```
  context 'ユーザーidが指定されている' do
    context '存在するユーザーidが指定されている' do
      # titleとかcontentが正しければcreate成功する
    end

    context '存在しないユーザーidが指定されている' do
        # createが失敗
      end
    end
  end

  context 'ユーザーidが指定されていない' do
    # createが失敗
  end
```

という感じになるかなと。

もちろんこのテストケースがBESTだとは思っていないのですが

> 表現に関しては例えば、一番上のcontextをユーザーがログインしている場合にして、次のcontextをtitleが存在しない場合そしてitをjournalが作成されないにすると思います。

がちょっとどういうケース分けになるのかがわからなかったので、追加説明願いたいです。

2023-07-11 11:28 UTC, DaisukeShinoku commented on backend/spec/requests/journal/delete_journal_spec.rb
> +end
> 「存在するjournalを削除をしようとする場合」は自分なら「対象のJournalが存在している場合」にしますね。

良さそう、他の部分と一緒に修正します！

2023-07-11 11:45 UTC, DaisukeShinoku commented on backend/spec/requests/journal/create_journal_spec.rb
> +          expect(e.record.errors.full_messages).to include("Title can't be blank")
> このテストケースだと「エラーメッセージが返ること」をテストしているように思います

これはその通りで、graphqlのmutationに対してであればそれがテスト内容になるという理解をしていた感じですかね

APIサーバーのテストなので
・成功の場合は、引数に応じたjournalが作成されている
・失敗の場合は、エラーを返却している
というテストでいいかな〜という考えでこの書き方をしている感じです

P.S.
be_invalidを使ってrequest specってなるとちょっと書き方パッと思いつかないかもです

2023-07-16 07:17 UTC, shikata1112 commented on backend/spec/requests/journal/create_journal_spec.rb
> +  let(:user) { FactoryBot.create(:user) }
[imo]
rails_helperの記述のおかげでクラス名が省略できるようになってます🙋‍♂️

```suggestion
  let(:user) { create(:user) }
```

https://github.com/yuki-snow1823/diary/blob/ba5b21ee23fd4ec2b35b35b0d9f38f38880e0f17/backend/spec/rails_helper.rb#L64

2023-07-16 07:35 UTC, shikata1112 commented on backend/spec/requests/journal/create_journal_spec.rb
> +          expect(e.record.errors.full_messages).to include("Title can't be blank")
（個人的な感想です）
今回はtitleが存在しない場合はjournalのレコードが作成されないということを期待値として確認していた方が無難かなと思いました！

今回は関係ないですが例えばトランザクションの考慮忘れていて、実装ミスでエラーメッセージが返るが、レコードは作成されていたなんてことありそうだなと思いました。

`.not_to change` or `.to avoid_changing`あたりでレコードが作成されていないことを確認できるとベストかなという意見です🙋‍♂️

2023-07-20 12:23 UTC, DaisukeShinoku commented
https://github.com/yuki-snow1823/diary/pull/73
でやるよ

2023-07-20 12:23 UTC, closed without merging